// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/authorization.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationRequest) Reset() {
	*x = AuthorizationRequest{}
	mi := &file_proto_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationRequest) ProtoMessage() {}

func (x *AuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationRequest.ProtoReflect.Descriptor instead.
func (*AuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_proto_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthorizationRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AuthorizationRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *AuthorizationRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type AuthorizationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AuthCode        string                 `protobuf:"bytes,2,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CardStatus      string                 `protobuf:"bytes,4,opt,name=card_status,json=cardStatus,proto3" json:"card_status,omitempty"`
	ApprovedLimit   float64                `protobuf:"fixed64,5,opt,name=approved_limit,json=approvedLimit,proto3" json:"approved_limit,omitempty"`
	RequestedAmount float64                `protobuf:"fixed64,6,opt,name=requested_amount,json=requestedAmount,proto3" json:"requested_amount,omitempty"`
	LimitSufficient bool                   `protobuf:"varint,7,opt,name=limit_sufficient,json=limitSufficient,proto3" json:"limit_sufficient,omitempty"`
	Message         string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthorizationResponse) Reset() {
	*x = AuthorizationResponse{}
	mi := &file_proto_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationResponse) ProtoMessage() {}

func (x *AuthorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationResponse.ProtoReflect.Descriptor instead.
func (*AuthorizationResponse) Descriptor() ([]byte, []int) {
	return file_proto_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizationResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *AuthorizationResponse) GetAuthCode() string {
	if x != nil {
		return x.AuthCode
	}
	return ""
}

func (x *AuthorizationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuthorizationResponse) GetCardStatus() string {
	if x != nil {
		return x.CardStatus
	}
	return ""
}

func (x *AuthorizationResponse) GetApprovedLimit() float64 {
	if x != nil {
		return x.ApprovedLimit
	}
	return 0
}

func (x *AuthorizationResponse) GetRequestedAmount() float64 {
	if x != nil {
		return x.RequestedAmount
	}
	return 0
}

func (x *AuthorizationResponse) GetLimitSufficient() bool {
	if x != nil {
		return x.LimitSufficient
	}
	return false
}

func (x *AuthorizationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_authorization_proto protoreflect.FileDescriptor

const file_proto_authorization_proto_rawDesc = "" +
	"\n" +
	"\x19proto/authorization.proto\x12\rauthorization\"\x87\x01\n" +
	"\x14AuthorizationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\"\xab\x02\n" +
	"\x15AuthorizationResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1b\n" +
	"\tauth_code\x18\x02 \x01(\tR\bauthCode\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vcard_status\x18\x04 \x01(\tR\n" +
	"cardStatus\x12%\n" +
	"\x0eapproved_limit\x18\x05 \x01(\x01R\rapprovedLimit\x12)\n" +
	"\x10requested_amount\x18\x06 \x01(\x01R\x0frequestedAmount\x12)\n" +
	"\x10limit_sufficient\x18\a \x01(\bR\x0flimitSufficient\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage2p\n" +
	"\x14AuthorizationService\x12X\n" +
	"\tAuthorize\x12#.authorization.AuthorizationRequest\x1a$.authorization.AuthorizationResponse\"\x00B\x1aZ\x18service-a/internal/pb;pbb\x06proto3"

var (
	file_proto_authorization_proto_rawDescOnce sync.Once
	file_proto_authorization_proto_rawDescData []byte
)

func file_proto_authorization_proto_rawDescGZIP() []byte {
	file_proto_authorization_proto_rawDescOnce.Do(func() {
		file_proto_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_authorization_proto_rawDesc), len(file_proto_authorization_proto_rawDesc)))
	})
	return file_proto_authorization_proto_rawDescData
}

var file_proto_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_authorization_proto_goTypes = []any{
	(*AuthorizationRequest)(nil),  // 0: authorization.AuthorizationRequest
	(*AuthorizationResponse)(nil), // 1: authorization.AuthorizationResponse
}
var file_proto_authorization_proto_depIdxs = []int32{
	0, // 0: authorization.AuthorizationService.Authorize:input_type -> authorization.AuthorizationRequest
	1, // 1: authorization.AuthorizationService.Authorize:output_type -> authorization.AuthorizationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_authorization_proto_init() }
func file_proto_authorization_proto_init() {
	if File_proto_authorization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_authorization_proto_rawDesc), len(file_proto_authorization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_authorization_proto_goTypes,
		DependencyIndexes: file_proto_authorization_proto_depIdxs,
		MessageInfos:      file_proto_authorization_proto_msgTypes,
	}.Build()
	File_proto_authorization_proto = out.File
	file_proto_authorization_proto_goTypes = nil
	file_proto_authorization_proto_depIdxs = nil
}
